# Generated by Django 3.2.4 on 2021-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacinacao',
            name='enfermeiro',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
