# Generated by Django 3.2.4 on 2021-06-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crianca_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crianca',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
